-- deterministic fixture output generated by sandbox fallback
local function main()
  local total = 0
  for i = 1, 3 do
    total = total + i
  end
  return total
end

return {
  entry = main,
  result = main()
}
