from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from src.tools.annotate_output import annotate_output


def _write_pipeline(tmp_path: Path) -> Path:
    payload = {
        "pipelines": [
            {
                "sequence": ["string-escape", "prga", "permute"],
                "confidence": 0.85,
                "version_hint": "v14.4.2",
            }
        ]
    }
    path = tmp_path / "pipeline_candidates.json"
    path.write_text(json.dumps(payload), encoding="utf-8")
    return path


def test_annotate_output_inserts_header(tmp_path: Path) -> None:
    output = tmp_path / "deobfuscated_pretty.lua"
    original = "print('hello world')\n"
    output.write_text(original, encoding="utf-8")
    pipeline_path = _write_pipeline(tmp_path)

    timestamp = datetime(2024, 1, 2, 3, 4, 5, tzinfo=timezone.utc)
    result = annotate_output(output, pipeline_path=pipeline_path, timestamp=timestamp)

    assert result.applied
    text = output.read_text(encoding="utf-8")
    lines = text.splitlines()
    assert lines[0] == "--[["
    assert lines[1] == "-- PROVENANCE (annotate_output): generated 2024-01-02T03:04:05Z"
    assert lines[2] == "-- PIPELINE: string-escape -> prga -> permute"
    assert lines[3] == "-- VERSION_HINT: v14.4.2"
    assert lines[4] == "-- CONFIDENCE: 0.850"
    assert lines[5].startswith("-- Generated by src.tools.annotate_output")
    assert lines[6] == "--]]"
    assert "print('hello world')" in text


def test_annotate_output_replaces_existing_header(tmp_path: Path) -> None:
    output = tmp_path / "pretty.lua"
    output.write_text("return 1\n", encoding="utf-8")
    pipeline_path = _write_pipeline(tmp_path)

    first_time = datetime(2024, 1, 2, 3, 4, 5, tzinfo=timezone.utc)
    annotate_output(output, pipeline_path=pipeline_path, timestamp=first_time)
    second_time = datetime(2025, 6, 7, 8, 9, 10, tzinfo=timezone.utc)
    annotate_output(output, pipeline_path=pipeline_path, timestamp=second_time)

    text = output.read_text(encoding="utf-8")
    assert text.count("-- PROVENANCE (annotate_output):") == 1
    assert "2025-06-07T08:09:10Z" in text


def test_annotate_output_disable_removes_header(tmp_path: Path) -> None:
    output = tmp_path / "beautified.lua"
    original = "local x = 1\n"
    output.write_text(original, encoding="utf-8")
    pipeline_path = _write_pipeline(tmp_path)

    annotate_output(output, pipeline_path=pipeline_path)
    annotate_output(output, pipeline_path=pipeline_path, enabled=False)

    assert output.read_text(encoding="utf-8") == original
