name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt

      - name: Install LuaJIT & lua-cjson
        run: |
          sudo apt-get update
          sudo apt-get install -y luajit luarocks
          sudo luarocks install lua-cjson || true
          luajit -v || true

      - name: Run tests
        run: |
          . .venv/bin/activate
          pytest -q
